# Generated by Django 4.0.3 on 2022-03-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('datum', models.DateTimeField(auto_now=True)),
                ('pH', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SPO2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SPO2color', models.CharField(max_length=20)),
                ('turbidity', models.CharField(max_length=20)),
                ('bacteriaPhoto', models.ImageField(upload_to='')),
                ('nitrxPhoto', models.ImageField(upload_to='')),
            ],
        ),
    ]
